### ISSUE TITLE
Problem with Lazy things

### ISSUE THREAD

**Issue by AshantyTTV** [Tera-Shiraneko/lazy-steroids#1]
Ok so i am not so experienced but i think there is a problem.
Sometimes when i activate A-Rush or G-Shout or Infuriate it does not activates beer or Brooch. 

Also on Gunner it happens this. If i activate  Modular Weapon System it does not pop-up beer/brooch

I dont know what is going on. 
Also its possible to add pet skill as an update to be auto-casted with brooch/beer/petskill?

**Comment by Tera-Shiraneko** [comment]
Servant skill packet is not whitelisted so I can't add it. About the module not using the items shouldn't happen as long as its not on cd. Never got any issues on any class rn.
